language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"
install: 
   - pip install -r requirements.txt
   - pip install codecov

script:
  #- python backup.py
  - coverage run run_server.py

after_success:
- codecov
