language: python

python:
  - 2.7
  - 3.7
install: 
  - pip install -r requirements.txt
  - pip install codecov

script:
  #- python backup.py
  - coverage run run_server.py

after_success:
  - codecov
